### **Numpy Intro**

In [ ]:
import numpy as np
import sys
import time

In [ ]:
a = np.array([10, 20, 30])

In [ ]:
a[0], a[1]

(np.int64(10), np.int64(20))

3 main benefits of numpy array over a python list,

1. Less Memory
2. Fast
3. Convinient

In [ ]:
lst = range(1000)
print(sys.getsizeof(5)*len(lst))

28000


In [ ]:
print(sys.getsizeof(10)) #int
print(sys.getsizeof(15.5)) #float
print(sys.getsizeof(True)) #boolean
print(sys.getsizeof('Hey')) #string

28
24
28
44


In [ ]:
arr = np.arange(100)
print(arr)

print(arr.size)
print(arr.itemsize)
print(arr.size*arr.itemsize)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
100
8
800


We will add two list of numbers using python list and numpy array and compare them

In [ ]:
size = 100

lst1 = range(size)
lst2 = range(size)

# python list
start = time.time()
result = [(x+y) for x,y in zip(lst1,lst2)]
print('Python list took :', (time.time()-start)*1000)

Python list took : 0.1838207244873047


In [ ]:
a1 = np.arange(size)
a2 = np.arange(size)

#numpy array
start = time.time()
result = a1 + a2
print('numpy array took :', (time.time()-start)*1000)

numpy array took : 0.1614093780517578


Numpy operations

In [ ]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])

In [ ]:
a1+a2

array([5, 7, 9])

In [ ]:
a1-a2

array([-3, -3, -3])

In [ ]:
a1*a2

array([ 4, 10, 18])

In [ ]:
a1/a2

array([0.25, 0.4 , 0.5 ])

### **Numpy Basic array operations**

In [ ]:
a = np.array([5, 6, 9])

In [ ]:
print(a[0])
print(a[2])
print(a.ndim)

5
9
1


In [ ]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a)
print(a.ndim)
print(a.shape)
print(a.dtype)
print(a.itemsize)

[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)
int64
8


In [ ]:
a = np.array([[1, 2], [3, 4], [5, 6]], dtype=np.float64)

In [ ]:
print(a)
print(a.itemsize)
print(a.dtype)
print(a.ndim)
print(a.shape)

[[1. 2.]
 [3. 4.]
 [5. 6.]]
8
float64
2
(3, 2)


In [ ]:
a = np.array([[[1, 2], [3, 4], [5, 6]], [[10, 2], [50, 60], [80, 90]]], dtype=np.float64)

In [ ]:
print(a)
print(a.ndim)
print(a.shape)

[[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[10.  2.]
  [50. 60.]
  [80. 90.]]]
3
(2, 3, 2)


In [ ]:
a = np.array([[1, 2], [3, 4], [5, 6]], dtype=complex)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [ ]:
a = np.zeros((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
a = np.ones((3, 4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# List
l = range(5)

print(l[0])
print(l[4])

0
4


In [ ]:
np.arange(1, 5)

array([1, 2, 3, 4])

In [ ]:
np.arange(1, 5, 2)

array([1, 3])

In [ ]:
a = np.linspace(1, 5, 5)
print(a)

[1. 2. 3. 4. 5.]


In [ ]:
a = np.linspace(1, 5, 10)
print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


### **Reshape**

In [ ]:
a = np.array([[1,2], [3,4], [5,6]])
print(a)
print(a.shape)
print('\n')

a = a.reshape(2, 3)
print(a)
print(a.shape)
print('\n')

a = a.reshape(6, 1)
print(a)
print(a.shape)
print('\n')

a = a.ravel()
print(a)
print(a.shape)
print('\n')

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


[[1 2 3]
 [4 5 6]]
(2, 3)


[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


[1 2 3 4 5 6]
(6,)




### **Min/Max and Sum**

In [ ]:
a = np.array([[1,2], [3,4], [5,6]])
print(a)
print(a.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [ ]:
a.max()

np.int64(6)

In [ ]:
a.min()

np.int64(1)

In [ ]:
a.sum()

np.int64(21)

In [ ]:
a.sum(axis=0)

array([ 9, 12])

In [ ]:
a.sum(axis=1)

array([ 3,  7, 11])

In [ ]:
# Square root
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [ ]:
# Standar deviation

np.std(a)

np.float64(1.707825127659933)

In [ ]:
np.mean(a)

np.float64(3.5)

In [ ]:
np.median(a)

np.float64(3.5)

### **Operations in Array**

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [ ]:
a+b

array([[ 6,  8],
       [10, 12]])

In [ ]:
a-b

array([[-4, -4],
       [-4, -4]])

In [ ]:
a*b

array([[ 5, 12],
       [21, 32]])

In [ ]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [ ]:
# dot product
a.dot(b)

array([[19, 22],
       [43, 50]])

### **Slicing indexing with boolean arrays**

In [ ]:
a = np.array([6, 7, 8])
a[0:2]

array([6, 7])

In [ ]:
print(a[-1])
print(a[1])

8
7


In [ ]:
# 2D array

a = np.array([[6, 7, 8], [1, 3, 2], [9, 3, 3]])
a

array([[6, 7, 8],
       [1, 3, 2],
       [9, 3, 3]])

In [ ]:
print(a[1, 2])
print(a[2, 0])

2
9


In [ ]:
print(a[0:2, 2], '\n')
print(a[1:, 1:], '\n')
print(a[:, 1:3], '\n')

[8 2] 

[[3 2]
 [3 3]] 

[[7 8]
 [3 2]
 [3 3]] 



Iterate through arrays

In [ ]:
a = np.array([[6, 7, 8], [1, 2, 3], [9, 1, 5]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 1, 5]])

In [ ]:
# Iterating the complete matrix/numpy array
for row in a:
  # print(row)
  lst = row
  for i in lst:
    print(i, end=' ')
  print()

6 7 8 
1 2 3 
9 1 5 


In [ ]:
for num in a.flat:
  print(num)

6
7
8
1
2
3
9
1
5


In [ ]:
for num in a.ravel():
  print(num)

6
7
8
1
2
3
9
1
5


### **Stacking together two arrays**

In [ ]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b = np.arange(7, 13).reshape(2, 3)
b

array([[ 7,  8,  9],
       [10, 11, 12]])

**Vertical & Horizontal Stacking**

In [ ]:
np.vstack((a, b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.vstack((b, a))

array([[ 7,  8,  9],
       [10, 11, 12],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [ ]:
np.hstack((a, b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [ ]:
np.hstack((b, a))

array([[ 7,  8,  9,  1,  2,  3],
       [10, 11, 12,  4,  5,  6]])

**Splitting an array into small arrays**

In [ ]:
a = np.arange(30).reshape(2, 15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

Horizontal Split

In [ ]:
result = np.hsplit(a, 3)
result

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [ ]:
print(result[0])
print(result[1])
print(result[2])

[[ 0  1  2  3  4]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [20 21 22 23 24]]
[[10 11 12 13 14]
 [25 26 27 28 29]]


Vertical Split

In [ ]:
result = np.vsplit(a, 2)
result

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [ ]:
print(result[0])
print(result[1])

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]
[[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]


Indexing with boolean array

In [ ]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [ ]:
a[a<4]*10

array([ 0, 10, 20, 30])

In [ ]:
a[a>4]=-1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

### **Iterate Numpy array using nditer**

In [ ]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
for row in a:
  for cell in row:
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [ ]:
for cell in a.flatten():
  print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


### **Numpy function nditer() function**

In [ ]:
for x in np.nditer(a, order='C'):
  print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [ ]:
for x in np.nditer(a, order='F'):
  print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [ ]:
for x in np.nditer(a, order='C', flags=['external_loop']):
  print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


### Op_flags on for loop

In [ ]:
for x in np.nditer(a, op_flags=['readwrite']):
  x[...] = x*x

a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
# for x in np.nditer(a, op_flags=['readwrite']):
#   x[...] = x*10

# a

### Iterate two arrays

In [ ]:
b = np.arange(5, 8).reshape(3, 1)
b

array([[5],
       [6],
       [7]])

In [ ]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
for x,y in np.nditer([a, b]):
  print(x, y)

0 5
1 5
4 5
9 5
16 6
25 6
36 6
49 6
64 7
81 7
100 7
121 7


In [ ]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
a[1, 1] += 10
a

array([[  0,   1,   4,   9],
       [ 16,  35,  36,  49],
       [ 64,  81, 100, 121]])