<a href="https://colab.research.google.com/github/rishav197/Python/blob/main/python/numpy_part2_May11_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# 1D array
a1 = np.array([10, 20, 30])

# 2D array
a2 = np.array([[10, 20],
             [30, 40]])

# 3D array
a3 = np.array([[[10, 20],
                [30, 40]],
               [[50, 60],
                [70, 80]],
               [[90, 100],
                [110, 120]]])

In [ ]:
print(a1.shape)
print(a2.shape)
print(a3.shape)

(3,)
(2, 2)
(3, 2, 2)


In [ ]:
a = np.array([10, 20, 30])

print(a[0])
print(a[1])

10
20


**3 main benefits of numpy array over a python list,** <br>

1. Less Memory
2. Fast
3. Convinient


In [ ]:
import sys

In [ ]:
lst = range(1000)
print(sys.getsizeof(5)*len(lst))

28000


In [ ]:
lst = np.arange(10)
print(lst)
print(lst.size*lst.itemsize)

[0 1 2 3 4 5 6 7 8 9]
80


We will add two list of numbers using python list and numpy array and compare them

In [ ]:
import time

In [ ]:
size = 1000

l1 = range(size)
l2 = range(size)

# python list
start = time.time()
result = [(x+y) for x,y in zip(l1, l2)]

# print(result)
print(f"Time taken by Python List : {(time.time()-start)*1000}")

Time taken by Python List : 0.3883838653564453


In [ ]:
size = 1000

a1 = np.arange(size)
a2 = np.arange(size)

#numpy array
start = time.time()
result = a1 + a2

# print(result)
print(f"Time taken by Numpy Array : {(time.time()-start)*1000}")

Time taken by Numpy Array : 0.18286705017089844


Numpy Operations

In [ ]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])

a1 + a2

array([5, 7, 9])

In [ ]:
a2 - a1

array([3, 3, 3])

In [ ]:
a1 * a2

array([ 4, 10, 18])

In [ ]:
a1 / a2

array([0.25, 0.4 , 0.5 ])

In [ ]:
a = np.array([5, 6, 9])

In [ ]:
print(a[0])
print(a[2])
print(a.ndim)

5
9
1


In [ ]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a)
print(a.ndim)

[[1 2]
 [3 4]
 [5 6]]
2


In [ ]:
a = np.array([[[1, 2],
              [3, 4]],
             [[4, 5],
              [2,2.5]],
             [[2,2],
              [-4,-7]]])
print(a)
print(a.shape)
print(a.ndim)

[[[ 1.   2. ]
  [ 3.   4. ]]

 [[ 4.   5. ]
  [ 2.   2.5]]

 [[ 2.   2. ]
  [-4.  -7. ]]]
(3, 2, 2)
3


In [ ]:
print(a.itemsize)
print(a.dtype)

8
float64


In [ ]:
a = np.array([[1, 2], [3, 4], [5, 6]], dtype=np.float64)
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [ ]:
a = np.array([[1, 2], [3, 4], [5, 6]], dtype=np.float64)
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [ ]:
print(a.itemsize)
print(a.ndim)
print(a.size) #size = no. of elements (no. of rows x no. of cols)
print(a.shape)
print(a.dtype)

8
2
6
(3, 2)
float64


In [ ]:
a = np.array([[1, 2], [3, 4], [5, 6]], dtype=complex)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [ ]:
a = np.zeros((3, 1, 3))
print(a.shape)
print(a.ndim)
a

(3, 1, 3)
3


array([[[0., 0., 0.]],

       [[0., 0., 0.]],

       [[0., 0., 0.]]])

In [ ]:
a = np.ones((2, 3), dtype=int)
print(a.shape)
print(a.ndim)
a

(2, 3)
2


array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
a = np.arange(1, 5)
b = np.arange(1, 5, 2)

In [ ]:
print(a)
print(b)

[1 2 3 4]
[1 3]


In [ ]:
a = np.linspace(1, 5, 10)
a

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
a = np.linspace(1, 10, 5)
a

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
a = np.linspace(1, 10, 4) # start:stop:total_elements
a

array([ 1.,  4.,  7., 10.])

In [ ]:
a = np.linspace(1, 5, 5)
print(a)

[1. 2. 3. 4. 5.]


Reshape

In [ ]:
a = np.array([[1,2], [3,4], [5,6]])
print(a)
print(a.shape)
print('\n')

a = a.reshape(2,3)
print(a)
print(a.shape)
print('\n')

a = a.reshape(6, 1)
print(a)
print(a.shape, a.ndim)
print('\n')

a = a.reshape(1, 6)
print(a)
print(a.shape, a.ndim)
print('\n')

a = a.reshape(6,)
print(a)
print(a.shape, a.ndim)
print('\n')

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


[[1 2 3]
 [4 5 6]]
(2, 3)


[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1) 2


[[1 2 3 4 5 6]]
(1, 6) 2


[1 2 3 4 5 6]
(6,) 1




In [ ]:
a = np.array([[9,20], [13,14], [-5,61]])
print(a)
print(a.shape, a.ndim)
print('\n')

a = a.ravel() #flatten any array into 1D array
print(a)
print(a.shape, a.ndim)

[[ 9 20]
 [13 14]
 [-5 61]]
(3, 2) 2


[ 9 20 13 14 -5 61]
(6,) 1


Min/Max and Sum

In [ ]:
a = np.array([[1,2], [3,4], [5,6]])
print(a)
print(a.ndim, a.shape)

[[1 2]
 [3 4]
 [5 6]]
2 (3, 2)


In [ ]:
print(a.min())
print(a.max())
print(a.sum())

1
6
21


In [ ]:
print(a.sum(axis=0))
print(a.sum(axis=1))

[ 9 12]
[ 3  7 11]


Square root

In [ ]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [ ]:
# std deviation
np.std(a)

np.float64(1.707825127659933)

In [ ]:
a.mean()

np.float64(3.5)

Operations in Array

In [ ]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])

print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [ ]:
a+b

array([[ 6,  8],
       [10, 12]])

In [ ]:
a-b

array([[-4, -4],
       [-4, -4]])

In [ ]:
a*b

array([[ 5, 12],
       [21, 32]])

In [ ]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [ ]:
a.dot(b) #dot product

array([[19, 22],
       [43, 50]])

what is indexing and slicing

In [ ]:
lst = [6, 7, 8]
lst[0:2]

[6, 7]

In [ ]:
lst[-1]

8

In [ ]:
a = np.array([6, 7, 8])
a[0:2]

array([6, 7])

In [ ]:
a[-2]

np.int64(7)

In [ ]:
# 2D array
a = np.array([[6, 7, 8], [1, 2, 3], [9, 3, 2]])
a


array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [ ]:
print(a[1, 2])
print(a[2, 0])

3
9


In [ ]:
a[0:3, 2]

array([8, 3, 2])

In [ ]:
a[1:, 1:]

array([[2, 3],
       [3, 2]])

In [ ]:
a[:2, :2]

array([[6, 7],
       [1, 2]])

In [ ]:
a[:2, 1:]

array([[7, 8],
       [2, 3]])

In [ ]:
a[0]

array([6, 7, 8])

Iterate through arrays

In [ ]:
a = np.array([[6, 7, 8], [1, 2, 3], [9, 3, 2]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [ ]:
for row in a:
  print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [ ]:
for row in a:
  for num in row:
    print(num, end=' ')

6 7 8 1 2 3 9 3 2 

In [ ]:
for num in a.flat:
  print(num, end=' ')

6 7 8 1 2 3 9 3 2 

In [ ]:
for num in a.ravel():
  print(num, end=' ')

6 7 8 1 2 3 9 3 2 

In [ ]:
a = np.arange(0, 6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
a = np.arange(0, 6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

Stacking

In [ ]:
a = np.arange(0, 6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
b = np.arange(6, 12).reshape(3, 2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
# Vertical Stacking
vs = np.vstack((a, b))
vs

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
vs = np.vstack((b, a))
vs

array([[ 6,  7],
       [ 8,  9],
       [10, 11],
       [ 0,  1],
       [ 2,  3],
       [ 4,  5]])

In [ ]:
# Horizontal Stacking
vs = np.hstack((a, b))
vs

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [ ]:
vs = np.hstack((b, a))
vs

array([[ 6,  7,  0,  1],
       [ 8,  9,  2,  3],
       [10, 11,  4,  5]])

Splitting an array into small arrays

In [ ]:
a = np.arange(30).reshape(2, 15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
result = np.hsplit(a, 3)
result

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [ ]:
print(result[0])
print(result[1])
print(result[2])

[[ 0  1  2  3  4]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [20 21 22 23 24]]
[[10 11 12 13 14]
 [25 26 27 28 29]]


In [ ]:
result = np.vsplit(a, 2)
result

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [ ]:
print(result[0], result[0].ndim)
print(result[1], result[1].ndim)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]] 2
[[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]] 2


Indexing with boolean array

In [ ]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b = a > 5
b

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
a[a > 5]

array([ 6,  7,  8,  9, 10, 11])

In [ ]:
a[a > 5] = -1

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5, -1, -1],
       [-1, -1, -1, -1]])

In [ ]:
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
a[...] = a*a
a

array([[ 0,  1,  4],
       [ 9, 16, 25]])

Iterate two arrays

In [ ]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b = np.arange(3, 15, 4).reshape(3, 1)
b

array([[ 3],
       [ 7],
       [11]])

In [ ]:
for x,y in np.nditer([a, b]):
  print(x, y)

0 3
1 3
2 3
3 3
4 7
5 7
6 7
7 7
8 11
9 11
10 11
11 11


In [ ]:
for x,y in np.nditer([b, a]):
  print(x, y)

3 0
3 1
3 2
3 3
7 4
7 5
7 6
7 7
11 8
11 9
11 10
11 11
