### **Imports**

In [83]:
import numpy as np

### **what is indexing and slicing**

In [84]:
lst = [6, 7, 8]
lst[0:2]

[6, 7]

In [85]:
lst[-1]

8

In [86]:
a = np.array([6, 7, 8])
a[0:2]

array([6, 7])

In [87]:
a[-1]

np.int64(8)

In [88]:
a = np.array([[6, 7, 8], [1, 2, 3], [9, 3, 2]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [89]:
a[1, 2] #print single item

np.int64(3)

In [90]:
a[0:2, 2]

array([8, 3])

In [91]:
a[1:, 1:]

array([[2, 3],
       [3, 2]])

In [92]:
a[-1]

array([9, 3, 2])

In [93]:
a[-1, 0:2]

array([9, 3])

In [94]:
a[:, 1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

### **Iterate through arrays**

In [95]:
a = np.array([[6, 7, 8], [1, 2, 3], [9, 3, 2]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [96]:
for row in a:
  print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [97]:
for row in a:
  # print(row)
  lst = row
  for i in lst:
    print(i, end=" ")
  print()

6 7 8 
1 2 3 
9 3 2 


In [98]:
for cell in a.flat:
  print(cell)

6
7
8
1
2
3
9
3
2


In [99]:
for cell in a.ravel():
  print(cell)

6
7
8
1
2
3
9
3
2


### **Stacking together two arrays**

In [100]:
a = np.arange(0,6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [101]:
b = np.arange(6,12).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

Vertical Stacking

In [102]:
np.vstack((a, b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [103]:
np.vstack((b, a))

array([[ 6,  7],
       [ 8,  9],
       [10, 11],
       [ 0,  1],
       [ 2,  3],
       [ 4,  5]])

Horizontal Stacking

In [104]:
np.hstack((a, b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [105]:
np.hstack((b, a))

array([[ 6,  7,  0,  1],
       [ 8,  9,  2,  3],
       [10, 11,  4,  5]])

### **Splitting an array into small arrays**

In [106]:
a = np.arange(30).reshape(2, 15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [107]:
result = np.hsplit(a, 3)

In [108]:
print(result[0])
print(result[1])
print(result[2])

[[ 0  1  2  3  4]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [20 21 22 23 24]]
[[10 11 12 13 14]
 [25 26 27 28 29]]


In [109]:
result = np.vsplit(a, 2)

In [110]:
print(result[0])
print(result[1])

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]
[[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]


### **Indexing with boolean array**

In [111]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [112]:
b = a > 4

b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [113]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [114]:
a[b] = -1

In [115]:
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])