In [197]:
import numpy as np

In [198]:
a = np.array([5, 6, 9])

In [199]:
print(a[0])
print(a[2])
print(a.ndim)

5
9
1


In [200]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a)
print(a.ndim)

[[1 2]
 [3 4]
 [5 6]]
2


In [201]:
print(a.itemsize)
print(a.dtype)

8
int64


In [202]:
a = np.array([[1, 2], [3, 4], [5, 6]], dtype=np.float64)

In [203]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [204]:
print(a.itemsize)
print(a.ndim)
print(a.size) #size = no. of elements (no. of rows x no. of cols)
print(a.shape)
print(a.dtype)

8
2
6
(3, 2)
float64


In [205]:
a = np.array([[1, 2], [3, 4], [5, 6]], dtype=complex)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [206]:
a = np.zeros((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [207]:
a = np.ones((3, 4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [208]:
# list
l = range(5)

print(l[0])
print(l[4])

0
4


In [209]:
np.arange(1, 5)

array([1, 2, 3, 4])

In [210]:
np.arange(1, 5, 2)

array([1, 3])

In [211]:
a = np.linspace(1, 5, 10) # start:stop:total_elements
print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [212]:
a = np.linspace(1, 5, 5)
print(a)

[1. 2. 3. 4. 5.]


In [213]:
a = np.linspace(1, 5, 20)
print(a)

[1.         1.21052632 1.42105263 1.63157895 1.84210526 2.05263158
 2.26315789 2.47368421 2.68421053 2.89473684 3.10526316 3.31578947
 3.52631579 3.73684211 3.94736842 4.15789474 4.36842105 4.57894737
 4.78947368 5.        ]


### Reshape

In [214]:
a = np.array([[1,2], [3,4], [5,6]])
print(a)
print(a.shape)
print('\n')

a = a.reshape(2,3)
print(a)
print(a.shape)
print('\n')

a = a.reshape(6,1)
print(a)
print(a.shape)
print('\n')

a = a.ravel() #flatten any array into 1d array
print(a)
print(a.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


[[1 2 3]
 [4 5 6]]
(2, 3)


[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


[1 2 3 4 5 6]
(6,)


###Min/Max and Sum

In [216]:
a = np.array([[1,2], [3,4], [5,6]])
print(a)
print(a.shape)


[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [217]:
a.min()

np.int64(1)

In [218]:
a.max()

np.int64(6)

In [220]:
a.sum() #sum of all elements of the arr

np.int64(21)

<img src="https://raw.githubusercontent.com/rishav197/Python/main/Numpy/numpy_axis.jpg" alt="numpy axis" width="300">

In [223]:
a.sum(axis=0)

array([ 9, 12])

In [224]:
a.sum(axis=1)

array([ 3,  7, 11])

In [225]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [226]:
# Square root

np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [228]:
# standard deviation
np.std(a)

np.float64(1.707825127659933)

### Operations in Array

In [230]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])

print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [231]:
a+b

array([[ 6,  8],
       [10, 12]])

In [232]:
a-b

array([[-4, -4],
       [-4, -4]])

In [233]:
a*b

array([[ 5, 12],
       [21, 32]])

In [234]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [235]:
# dot product
a.dot(b)

array([[19, 22],
       [43, 50]])