In [ ]:
import numpy as np

In [ ]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
for row in a:
  # print(row)
  for cell in row:
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [ ]:
for row in a:
  # print(row)
  for cell in row:
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [ ]:
for cell in a.flatten():
  print(cell)


0
1
2
3
4
5
6
7
8
9
10
11


### **numpy function nditer() function**

In [ ]:
for x in np.nditer(a, order='C'):
  print(x)

0
1
2
3
4
5
6
7
8
9
10
11


order
{‘C’, ‘F’, ‘A’, ‘K’}, optional
Controls the iteration order. ‘C’ means C order, ‘F’ means Fortran order, ‘A’ means ‘F’ order if all the arrays are Fortran contiguous, ‘C’ order otherwise, and ‘K’ means as close to the order the array elements appear in memory as possible. This also affects the element memory order of allocate operands, as they are allocated to be compatible with iteration order. Default is ‘K’.

In [ ]:
for x in np.nditer(a, order='F'):
  print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [ ]:
for x in np.nditer(a, order='F', flags=['external_loop']):
  print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


### **op_flags on for loop**

In [ ]:
for x in np.nditer(a, op_flags=['readwrite']):
  x[...] = x*x

In [ ]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
for x in np.nditer(a, op_flags=['readwrite']):
  x[...]= x*x

In [ ]:
a

array([[    0,     1,    16,    81],
       [  256,   625,  1296,  2401],
       [ 4096,  6561, 10000, 14641]])

### **Iterate two arrays**

In [ ]:
b = np.arange(3, 15, 4).reshape(3, 1)
b

array([[ 3],
       [ 7],
       [11]])

In [ ]:
for x,y in np.nditer([a, b]):
  print(x, y)

0 3
1 3
16 3
81 3
256 7
625 7
1296 7
2401 7
4096 11
6561 11
10000 11
14641 11


In [ ]:
for x,y in np.nditer([b, a]):
  print(x, y)

3 0
3 1
3 16
3 81
7 256
7 625
7 1296
7 2401
11 4096
11 6561
11 10000
11 14641
