In [50]:
import numpy as np
import sys
import time

In [51]:
a = np.array([10, 20, 30])

In [52]:
a[0], a[1]

(np.int64(10), np.int64(20))

**3 main benefits of numpy array over a python list,** <br>

1. Less Memory
2. Fast
3. convinient

In [53]:
l = range(1000)
print(sys.getsizeof(5)*len(l))

28000


In [54]:
array = np.arange(1000)
# print(array)
print(array.size*array.itemsize)

8000


We will add two list of numbers using python list and numpy array and compare them

In [55]:
size = 1000

l1 = range(size)
l2 = range(size)

# python list
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("python list took: ", (time.time()-start)*1000)

python list took:  0.38242340087890625


In [56]:
a1 = np.arange(size)
a2 = np.arange(size)

# numpy array
start = time.time()
result = a1 + a2
print("numpy took: ", (time.time()-start)*1000)

numpy took:  0.10919570922851562


In [57]:
# Numpy Operations

In [60]:
a1  = np.array([1, 2, 3])
a2  = np.array([4, 5, 6])

a1 + a2

array([5, 7, 9])

In [61]:
a2 - a1

array([3, 3, 3])

In [62]:
a1 * a2

array([ 4, 10, 18])

In [63]:
a1/a2

array([0.25, 0.4 , 0.5 ])